apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-deployment

spec:
  selector:
    matchLabels:
      app: wildfly
  replicas: 2
  template:
    metadata:
      labels:
        app: wildfly
    spec:
      containers:
      - name: wildfly
        image: fcusco96/wildfly-app:latest
        ports:
        - containerPort: 8080